# Generated by Django 2.2.6 on 2019-10-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_edition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_isbn',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pages',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_rating_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_review_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
